version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_planty
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: planty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  plantyapi:
    build:
      context: .
    container_name: plantyapi
    environment:
      ASPNETCORE_ENVIRONMENT: http
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
    app-network: