version: '3.8'

services:
  postgres_planty:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lazaro
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: planty
    ports:
      - "5432:5432"
    networks:
      - app-network

  plantyapi:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    container_name: plantyapi
    environment:
      ASPNETCORE_ENVIRONMENT: http
      ConnectionStrings__DefaultConnection: "Host=postgres_planty;Port=5432;Username=lazaro;Password=admin;Database=planty;"
    ports:
      - "5000:8080"
    depends_on:
      - postgres_planty
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
