version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_planty
    restart: always
    environment:
      POSTGRES_USER: lazaro
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: planty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  plantyapi:
    build:
      context: .
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    container_name: plantyapi
    environment:
      ASPNETCORE_ENVIRONMENT: http
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    command: >
      sh -c "until pg_isready -h postgres_planty -U lazaro; do echo 'Waiting for PostgreSQL...'; sleep 2; done && dotnet ef database update && dotnet API.dll"

volumes:
  postgres_data:

networks:
    app-network:
      driver: bridge